In [1]:
%pip install scikit-learn scikit-image

Note: you may need to restart the kernel to use updated packages.


In [2]:
import os
from skimage.io import imread
from skimage.transform import resize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [3]:
# PREPPING DATA
input_dir = "/home/ajm76/OrcaSeis/data"
categories = ['noise', 'orca_call']

In [8]:
data = []
labels = []
for category_idx, category in enumerate(categories):
    cat_path = ""
    if category == 'noise':
#         cat_path = 'noise_spectrograms' # actual code
        cat_path = 'noise_test' # just for testing
    else:
#         cat_path = 'orca_spectrograms' # actual code
        cat_path = 'orca_test'
    for file in os.listdir(os.path.join(input_dir, cat_path)):
        img_path = os.path.join(input_dir, cat_path, file)
        img = imread(img_path)
        img = resize(img, (15, 15))
        print(img)
        data.append(img.flatten())
        print(img.flatten())
        labels.append(category_idx)

[[[0.9989573  0.99790932 0.99831301 1.        ]
  [0.99066565 0.98054952 0.9848273  1.        ]
  [0.9877805  0.97359989 0.97941882 1.        ]
  [0.98718696 0.97311009 0.97922221 1.        ]
  [0.96594313 0.95191753 0.95807235 1.        ]
  [0.90790798 0.89353411 0.89924014 1.        ]
  [0.9114209  0.89654099 0.90119276 1.        ]
  [0.90864619 0.89365261 0.89815797 1.        ]
  [0.95805027 0.94291228 0.94668749 1.        ]
  [0.98805901 0.97322974 0.97814723 1.        ]
  [0.98834545 0.97375546 0.97913188 1.        ]
  [0.98914051 0.97664657 0.98162027 1.        ]
  [0.9946013  0.99187568 0.99210613 1.        ]
  [0.99206043 0.99198461 0.9915193  1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.98530749 0.96358714 0.97204829 1.        ]
  [0.87140069 0.66154855 0.75032509 1.        ]
  [0.83350895 0.54045854 0.66225621 1.        ]
  [0.82824201 0.53658365 0.66267302 1.        ]
  [0.82249563 0.52805029 0.64966693 1.        ]
  [0.80028684 0.49859269 0.60920122 1.

[[[0.99900692 0.99794046 0.99829252 1.        ]
  [0.99282711 0.98194335 0.98385325 1.        ]
  [0.99131396 0.97580543 0.97776499 1.        ]
  [0.99132682 0.97569418 0.97727412 1.        ]
  [0.97011891 0.95452383 0.95612948 1.        ]
  [0.91078468 0.89528995 0.89788112 1.        ]
  [0.91262731 0.89723248 0.90060815 1.        ]
  [0.91054747 0.89497763 0.89718966 1.        ]
  [0.95963075 0.94401564 0.94586131 1.        ]
  [0.99063233 0.97502142 0.9768471  1.        ]
  [0.99150397 0.97598541 0.97757366 1.        ]
  [0.99166191 0.97830331 0.98042408 1.        ]
  [0.99487654 0.99203453 0.9919883  1.        ]
  [0.99206094 0.99198489 0.99151914 1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.98672728 0.96445825 0.97145673 1.        ]
  [0.91607127 0.69061594 0.73043397 1.        ]
  [0.90453907 0.58425487 0.62971487 1.        ]
  [0.90760303 0.585405   0.62608827 1.        ]
  [0.89753229 0.57521048 0.61467004 1.        ]
  [0.84536498 0.5258199  0.58788098 1.

[[[0.99876498 0.99782677 0.99837618 1.        ]
  [0.98918901 0.97995304 0.98528992 1.        ]
  [0.98538391 0.97266058 0.98016248 1.        ]
  [0.98513232 0.97233883 0.97984363 1.        ]
  [0.96404817 0.95123786 0.95862974 1.        ]
  [0.90657436 0.89309528 0.89964802 1.        ]
  [0.90877995 0.89532707 0.90218066 1.        ]
  [0.90503058 0.89206649 0.89945859 1.        ]
  [0.95296157 0.94057034 0.94848678 1.        ]
  [0.98384912 0.97152822 0.97950213 1.        ]
  [0.98548433 0.97262977 0.98005003 1.        ]
  [0.98659805 0.97565917 0.98240144 1.        ]
  [0.99411519 0.99168519 0.9922541  1.        ]
  [0.99205598 0.99198281 0.9915207  1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.98327183 0.96267339 0.97274357 1.        ]
  [0.85812844 0.65608353 0.75448589 1.        ]
  [0.80340277 0.52841537 0.67191848 1.        ]
  [0.80007236 0.52600382 0.6714182  1.        ]
  [0.78902082 0.51622658 0.65989919 1.        ]
  [0.76926099 0.48736709 0.61961145 1.

[[[9.97423524e-01 9.97423514e-01 9.97453942e-01 1.00000000e+00]
  [9.75968351e-01 9.75968326e-01 9.76263879e-01 1.00000000e+00]
  [9.67194126e-01 9.67194125e-01 9.67602692e-01 1.00000000e+00]
  [9.66816743e-01 9.66816743e-01 9.67227134e-01 1.00000000e+00]
  [9.45647454e-01 9.45647454e-01 9.46057846e-01 1.00000000e+00]
  [8.87020864e-01 8.87020864e-01 8.87431255e-01 1.00000000e+00]
  [8.89433847e-01 8.89433847e-01 8.89844239e-01 1.00000000e+00]
  [8.86480890e-01 8.86480887e-01 8.86891307e-01 1.00000000e+00]
  [9.35298804e-01 9.35298802e-01 9.35709216e-01 1.00000000e+00]
  [9.66292091e-01 9.66292091e-01 9.66702483e-01 1.00000000e+00]
  [9.67080929e-01 9.67080924e-01 9.67491043e-01 1.00000000e+00]
  [9.70990678e-01 9.70987361e-01 9.71321089e-01 1.00000000e+00]
  [9.90779643e-01 9.90686143e-01 9.89909143e-01 1.00000000e+00]
  [9.92025174e-01 9.91973569e-01 9.91499477e-01 1.00000000e+00]
  [9.98889430e-01 9.98888937e-01 9.98884405e-01 1.00000000e+00]]

 [[9.53581990e-01 9.53580949e-01 9.542

[[[0.99781244 0.99755044 0.99817373 1.        ]
  [0.98037324 0.97722823 0.98386831 1.        ]
  [0.97320794 0.96886872 0.97815685 1.        ]
  [0.97296614 0.96848715 0.97792841 1.        ]
  [0.95169857 0.94734333 0.95663646 1.        ]
  [0.89316356 0.88870413 0.89805401 1.        ]
  [0.89583437 0.89115185 0.90068241 1.        ]
  [0.89292958 0.88824122 0.89775747 1.        ]
  [0.94180506 0.93703705 0.94658805 1.        ]
  [0.97241762 0.96799587 0.9773361  1.        ]
  [0.97350873 0.96879964 0.97836228 1.        ]
  [0.97627694 0.97246469 0.98059724 1.        ]
  [0.99183436 0.99099574 0.991843   1.        ]
  [0.99203461 0.99197638 0.99151706 1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.96102711 0.95625307 0.96831421 1.        ]
  [0.64914515 0.59351482 0.7200339  1.        ]
  [0.52394247 0.44507876 0.62277183 1.        ]
  [0.52225704 0.44223134 0.62126352 1.        ]
  [0.50809828 0.4313865  0.60663498 1.        ]
  [0.47402897 0.39574324 0.57190621 1.

[[[0.99772654 0.99753371 0.99805636 1.        ]
  [0.97932665 0.97708831 0.98274568 1.        ]
  [0.97200123 0.96876795 0.97684851 1.        ]
  [0.97210789 0.96835856 0.97689373 1.        ]
  [0.95065341 0.94718521 0.95550235 1.        ]
  [0.89232764 0.88855693 0.89715076 1.        ]
  [0.89461786 0.89097013 0.89937527 1.        ]
  [0.89163066 0.88801362 0.89645202 1.        ]
  [0.9408037  0.93680108 0.94550324 1.        ]
  [0.97119455 0.96784212 0.97596785 1.        ]
  [0.97242413 0.96863689 0.97724129 1.        ]
  [0.9758888  0.97233009 0.98006116 1.        ]
  [0.99175745 0.99097102 0.99170706 1.        ]
  [0.99203372 0.99197618 0.99151555 1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.95898153 0.95580006 0.96522401 1.        ]
  [0.62867126 0.58999704 0.69388866 1.        ]
  [0.4994938  0.44139782 0.59181059 1.        ]
  [0.50087766 0.43864899 0.59262878 1.        ]
  [0.48681462 0.42753236 0.57878303 1.        ]
  [0.45481999 0.39183404 0.54661546 1.

[[[0.99828289 0.99765821 0.99841736 1.        ]
  [0.98414837 0.97819888 0.98555452 1.        ]
  [0.97751197 0.97008155 0.97987    1.        ]
  [0.9734735  0.96882757 0.97748149 1.        ]
  [0.94901395 0.94722688 0.95315772 1.        ]
  [0.8898054  0.88848147 0.89366769 1.        ]
  [0.89165975 0.89075298 0.89512502 1.        ]
  [0.88910869 0.88795201 0.89299685 1.        ]
  [0.9383189  0.93684177 0.942465   1.        ]
  [0.96936246 0.96778881 0.97343739 1.        ]
  [0.970566   0.96863287 0.97489419 1.        ]
  [0.9735372  0.97231126 0.9770372  1.        ]
  [0.99140564 0.99097266 0.99126319 1.        ]
  [0.99203207 0.9919763  0.99151374 1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.97157459 0.95856306 0.97386798 1.        ]
  [0.72881563 0.61179188 0.75705874 1.        ]
  [0.60577972 0.46470008 0.65519512 1.        ]
  [0.53565433 0.4459027  0.60925138 1.        ]
  [0.45267266 0.42151878 0.52329719 1.        ]
  [0.40480999 0.38344941 0.47086188 1.

[[[0.99767116 0.99752946 0.99797138 1.        ]
  [0.97924286 0.97703319 0.98244993 1.        ]
  [0.97268771 0.968708   0.97735345 1.        ]
  [0.97207598 0.96834071 0.97681439 1.        ]
  [0.95119327 0.94722697 0.95591938 1.        ]
  [0.89260413 0.88856226 0.89732951 1.        ]
  [0.89468776 0.89096475 0.89949396 1.        ]
  [0.89203492 0.88801864 0.89670913 1.        ]
  [0.94093385 0.93683498 0.94564516 1.        ]
  [0.971593   0.96780259 0.9763037  1.        ]
  [0.97257987 0.96861627 0.9773617  1.        ]
  [0.9758149  0.97233538 0.97999169 1.        ]
  [0.99179533 0.99097972 0.99175405 1.        ]
  [0.99203447 0.99197628 0.99151636 1.        ]
  [0.99888943 0.99888894 0.99888441 1.        ]]

 [[0.95850435 0.95570191 0.96431547 1.        ]
  [0.62832621 0.58904413 0.68979233 1.        ]
  [0.50622885 0.44060381 0.59602161 1.        ]
  [0.50103313 0.43801599 0.59073059 1.        ]
  [0.49705198 0.42858274 0.58852558 1.        ]
  [0.46037692 0.3923402  0.5518328  1.

In [5]:
data = np.asarray(data)
labels = np.asarray(labels)

In [6]:
# TRAIN/TEST SPLIT
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, 
                                                     shuffle=True, stratify=labels)

In [7]:
# TRAIN CLASSIFIER
classifier = SVC()

# actually training 12 classifiers, later choose best one
parameters = [{'gamma': [0.01, 0.001, 0.0001], 'C': [1, 10, 100, 1000]}]

# # only for test datasets
# cv = StratifiedKFold(n_splits=3)

grid_search = GridSearchCV(classifier, parameters) # remove cv=cv parameter for actual 
grid_search.fit(x_train, y_train)

ValueError: n_splits=5 cannot be greater than the number of members in each class.

In [ ]:
# TEST PERFORMANCE
# choose best classifier out of the 12
best_estimator = grid_search.best_estimator_
y_prediction = best_estimator.predict(x_test) 
score = accuracy_score(y_prediction, y_test)

print('{}% of samples were correctly classified'.format(str(score * 100)))